import test from 'node:test';import assert from 'node:assert/strict';
import {calculate,requiredCorpus,simulate,convertPlan,countdown,validate,lean,fat,barista,coast,goalCost,goalPlan,blendedReturn,yearFlows,stressTest} from '../dist/engine.js';
// Fixed fixture so the site's sample plan can change without changing what the tests check.
const demo = {name:'My freedom plan',age:32,retire:50,horizon:95,expenses:75000,leanExpenses:45000,fatExpenses:120000,baristaIncome:30000,baristaUntil:60,income:180000,assets:4500000,contribution:70000,inflation:5,preReturn:8,postReturn:6,stepUp:3,pension:0,pensionAge:60,withdrawalTax:0,volatility:12,goals:[],incomes:[]};
test('zero return, zero inflation retirement matches undiscounted cash flows',()=>{const p={...demo,age:40,retire:40,horizon:60,expenses:1000,assets:240000,inflation:0,postReturn:0,goals:[]};assert.equal(requiredCorpus(p),240000);assert.equal(simulate(p).firstShortfall,null);assert.equal(simulate({...p,assets:239999}).firstShortfall,59);});
test('solver funds retirement including an early goal',()=>{const p={...demo,goals:[{name:'Home',amount:2000000,age:35}]};const result=calculate(p);assert.equal(simulate(p,p.retire,result.requiredMonthly+1).firstShortfall,null);assert.notEqual(simulate(p,p.retire,Math.max(0,result.requiredMonthly-10)).firstShortfall,null);});
test('pension reduces requirement; additional goals increase it',()=>{assert.ok(requiredCorpus({...demo,pension:20000})<requiredCorpus(demo));assert.ok(requiredCorpus({...demo,goals:[{name:'Travel',amount:100000,age:60}]})>requiredCorpus(demo));});
test('currency conversion scales values and preserves forecast',()=>{const a=calculate(demo),b=calculate(convertPlan(demo,.012));assert.ok(Math.abs(b.target/a.target-.012)<1e-8);assert.equal(a.forecast,b.forecast);});
test('unreachable outcome is explicit',()=>{const p={...demo,assets:0,contribution:0};assert.equal(calculate(p).forecast,null);});
test('invalid horizons and nonfinite inputs rejected',()=>{assert.throws(()=>validate({...demo,horizon:40}));assert.throws(()=>validate({...demo,assets:NaN}));});
test('calendar countdown handles month ends and past dates',()=>{assert.deepEqual(countdown('2027-02-28',new Date(2027,0,31)),{years:0,months:1,days:0,past:false});assert.equal(countdown('2020-01-01').past,true);});

test('lean FIRE needs less and retires no later than the full plan',()=>{const p=structuredClone(demo),l=lean(p),r=calculate(p);assert.ok(l.target<r.target);assert.ok(Math.abs(l.target/r.target-p.leanExpenses/p.expenses)<1e-9);assert.ok(l.forecast<=r.forecast);assert.throws(()=>validate({...demo,leanExpenses:demo.expenses+1}));});
test('older plans without lean spending get a default',()=>{const p=structuredClone(demo);delete p.leanExpenses;validate(p);assert.equal(p.leanExpenses,Math.round(demo.expenses*0.6));});
test('coast number funds retirement with no further contributions',()=>{const p=structuredClone(demo),c=coast(p);assert.equal(simulate({...p,assets:c.todayNumber*1.0001},p.retire,0).firstShortfall,null);assert.notEqual(simulate({...p,assets:c.todayNumber*0.999},p.retire,0).firstShortfall,null);});
test('coast age is the earliest age contributions can stop',()=>{const p={...structuredClone(demo),contribution:110000},c=coast(p);assert.ok(c.age>p.age&&c.age<=p.retire);assert.equal(simulate(p,p.retire,p.contribution,c.age).firstShortfall,null);assert.notEqual(simulate(p,p.retire,p.contribution,c.age-1).firstShortfall,null);assert.equal(coast({...p,assets:c.todayNumber*1.01}).age,p.age);});
test('conversion scales lean spending',()=>{assert.ok(Math.abs(convertPlan(demo,.012).leanExpenses-demo.leanExpenses*.012)<1e-9);});

test('fat FIRE needs more and retires no earlier',()=>{const p=structuredClone(demo),f=fat(p),r=calculate(p);assert.ok(f.target>r.target);assert.ok(f.forecast===null||f.forecast>=r.forecast);assert.throws(()=>validate({...demo,fatExpenses:demo.expenses-1}));});
test('barista income lowers the target only while it lasts',()=>{const p=structuredClone(demo),r=calculate(p),b=barista(p);assert.ok(b.target<r.target);assert.ok(b.forecast<=r.forecast);assert.ok(Math.abs(barista({...p,baristaUntil:p.retire}).target-r.target)<1e-6);assert.ok(barista({...p,baristaUntil:70}).target<b.target);});
test('main plan ignores part-time income',()=>{assert.equal(calculate({...demo,baristaIncome:70000}).target,calculate(demo).target);});
test('older plans get fat and barista defaults',()=>{const p=structuredClone(demo);delete p.fatExpenses;delete p.baristaIncome;delete p.baristaUntil;validate(p);assert.equal(p.fatExpenses,Math.round(demo.expenses*1.5));assert.equal(p.baristaIncome,Math.round(demo.expenses*.4));assert.equal(p.baristaUntil,60);});

test('each goal inflates at its own rate; 0% keeps it fixed',()=>{const p=structuredClone(demo),g={name:'School',amount:1000000,age:42};assert.ok(Math.abs(goalCost(p,g)-1000000*1.05**10)<1e-6);assert.ok(Math.abs(goalCost(p,{...g,inflation:10})-1000000*1.1**10)<1e-6);assert.equal(goalCost(p,{...g,inflation:0}),1000000);assert.ok(requiredCorpus({...p,goals:[{...g,age:60,inflation:10}]})>requiredCorpus({...p,goals:[{...g,age:60}]}));});
test('money coming in improves the plan',()=>{const p=structuredClone(demo),r=calculate(p),w=calculate({...p,goals:[{name:'Bonus',amount:3000000,age:40,kind:'in'}]});assert.ok(w.requiredMonthly<r.requiredMonthly);assert.ok(w.forecast<=r.forecast);const late=requiredCorpus({...p,goals:[{name:'Sale',amount:1e10,age:90,kind:'in'}]});assert.ok(late>0);});
test('income streams: inflation-linked beats fixed; only counts while active',()=>{const p=structuredClone(demo),base=requiredCorpus(p),linked=requiredCorpus({...p,incomes:[{name:'Rent',monthly:20000,start:50,end:96,inflate:true}]}),fixed=requiredCorpus({...p,incomes:[{name:'Rent',monthly:20000,start:50,end:96,inflate:false}]}),outside=requiredCorpus({...p,incomes:[{name:'Job',monthly:20000,start:30,end:50,inflate:true}]});assert.ok(linked<fixed&&fixed<base);assert.equal(outside,base);assert.throws(()=>validate({...demo,incomes:[{name:'x',monthly:1,start:60,end:60,inflate:true}]}));});
test('conversion scales income streams',()=>{const c=convertPlan({...demo,incomes:[{name:'Rent',monthly:20000,start:50,end:90,inflate:true}]},.012);assert.ok(Math.abs(c.incomes[0].monthly-240)<1e-9);});

test('goal plan: level monthly amount exactly closes the gap',()=>{const p=structuredClone(demo),g={name:'School',amount:1500000,age:55,inflation:4,fund:{separate:true,saved:266140,ret:12,monthly:0}},gp=goalPlan(p,g);assert.ok(Math.abs(gp.target-1500000*1.04**23)<1e-6);assert.ok(Math.abs(gp.fvSaved-266140*1.12**23)<1e-6);const withNeeded=goalPlan(p,{...g,fund:{...g.fund,monthly:gp.monthlyNeeded}});assert.ok(withNeeded.shortfall<1e-6);for(const r of gp.routes){const lumpGrown=r.lump*1.12**23,fromMonthly=r.monthly===null?0:goalPlan(p,{...g,fund:{...g.fund,saved:0,monthly:r.monthly}}).projected;assert.ok(Math.abs(lumpGrown+fromMonthly-gp.gap)<1e-3);}});
test('separately funded goals leave the retirement plan alone',()=>{const p=structuredClone(demo),g={name:'Car',amount:1000000,age:40},shared=requiredCorpus({...p,goals:[{...g,age:60}]}),sep=requiredCorpus({...p,goals:[{...g,age:60,fund:{separate:true,saved:0,ret:8,monthly:0}}]});assert.ok(shared>requiredCorpus(p));assert.equal(sep,requiredCorpus(p));assert.throws(()=>validate({...demo,goals:[{...g,fund:{separate:true,saved:-1,ret:8,monthly:0}}]}));});
test('goal due now has only a lump-sum route',()=>{const p=structuredClone(demo),gp=goalPlan(p,{name:'Now',amount:100000,age:p.age});assert.equal(gp.monthlyNeeded,null);assert.equal(gp.routes.length,1);assert.equal(gp.routes[0].lump,100000);});

test('holdings set retirement investments and a size-weighted return',()=>{const p={...structuredClone(demo),holdings:[{name:'Stocks',cls:'Equity',region:'India',ret:13,amount:3000000},{name:'PF',cls:'Debt',region:'India',ret:7.5,amount:1000000}]};validate(p);assert.equal(p.assets,4000000);assert.ok(Math.abs(blendedReturn(p)-11.625)<1e-9);assert.equal(blendedReturn({...demo,holdings:[]}),null);assert.throws(()=>validate({...demo,holdings:[{name:'x',cls:'Crypto',region:'India',ret:5,amount:1}]}));assert.equal(convertPlan(p,.012).holdings[1].amount,12000);});

test('year flows explain each change in the projection',()=>{const p={...structuredClone(demo),goals:[{name:'Home',amount:2000000,age:40}]},pts=simulate(p).points;for(const q of [p,{...p,withdrawalTax:15}])for(const a of [35,40,60]){const pts=simulate(q).points,f=yearFlows(q,a),i=a-q.age,before=pts[i].balance,net=f.invest-f.spend+f.items.reduce((s,x)=>s+(x.kind==='in'?x.amount:-x.amount),0)-f.tax,r=a<q.retire?q.preReturn:q.postReturn;assert.ok(Math.abs(Math.max(0,before+net)*(1+r/100)-pts[i+1].balance)<1e-3);}assert.equal(yearFlows(p,40).items[0].name,'Home');});

test('tax on withdrawals grosses up everything the portfolio pays out',()=>{const p=structuredClone(demo);assert.ok(Math.abs(requiredCorpus({...p,withdrawalTax:20})-requiredCorpus(p)/0.8)<1e-3);const g=[{name:'Trip',amount:500000,age:60},{name:'Sale',amount:500000,age:61,kind:'in'}],f=yearFlows({...p,goals:g,withdrawalTax:20},60);assert.ok(Math.abs(f.tax-(f.spend+f.items[0].amount)*0.25)<1e-6);assert.equal(yearFlows({...p,goals:g,withdrawalTax:20},61).tax,yearFlows({...p,goals:g,withdrawalTax:20},61).spend*0.25);assert.ok(calculate({...p,withdrawalTax:20}).requiredMonthly>calculate(p).requiredMonthly);assert.throws(()=>validate({...demo,withdrawalTax:60}));});

test('stress test: zero volatility matches the steady projection',()=>{const p={...structuredClone(demo),volatility:0},s=stressTest(p,{paths:50});assert.equal(s.successRate,simulate(p).firstShortfall===null?1:0);assert.ok(Math.abs(s.bands.at(-1).p50-simulate(p).final)<1e-3);});
test('stress test is repeatable, and more volatility lowers success for a tight plan',()=>{const p={...structuredClone(demo),contribution:110000},a=stressTest(p,{paths:300,seed:7}),b=stressTest(p,{paths:300,seed:7});assert.equal(a.successRate,b.successRate);const calm=stressTest({...p,volatility:4},{paths:300,seed:7}),wild=stressTest({...p,volatility:25},{paths:300,seed:7});assert.ok(wild.successRate<calm.successRate);for(const x of a.bands)assert.ok(x.p10<=x.p50&&x.p50<=x.p90);});
test('safe spending reaches the confidence target',()=>{const p={...structuredClone(demo),contribution:110000},s=stressTest(p,{paths:200,seed:3,confidence:.9}),ok=stressTest({...p,expenses:s.safeExpenses*0.999,leanExpenses:Math.min(p.leanExpenses,s.safeExpenses*0.999)},{paths:200,seed:3});assert.ok(ok.successRate>=.9);});
test('a crash right after retiring hurts more than the same crash later',()=>{const p={...structuredClone(demo),contribution:110000},q=stressTest(p,{paths:10}).sequence;assert.ok(q.early.shortfall!==null&&q.early.shortfall<(q.late.shortfall??Infinity));});
